### ISSUE TITLE
.Rdata files

### ISSUE THREAD

**Issue by DataCyan28** [BiCroLab/BLISS_NatSciData#1]
Hi I am not sure if this is the right place to put this because it is the first time I am using a github repository. I tried running the analysis for NatSciData_Neuro. Did all the necessary steps to get the files and rename folders etc as suggested. But when running the analysis I realize that the Rdata folder is not there and that .Rdata files mentioned in the R markdown is not present in any of the folders. I would appreciate any suggestions. Thanks in advance.

**Comment by ljwharbers** [comment]
Hi,

First of, I'm very sorry for the late response. Unfortunately the main person responsible for the analysis and for the creation of this repository is working somewhere else now. I have tried searching for these files but I'm sorry to say that I am unable to find them anywhere. 

Sorry again for the late reply and that I couldn't more of more help.

Best,
Luuk
